name: simple-streamlit
dependencies:
  - python
  - pip
  - pip:
    - pandas
    - python-dotenv
    - streamlit
    - boto3
    - ipykernel
    - vaderSentiment
    - plotly==5.19.0
    # - scikit-learn
    # - seaborn